'use client';

import { useEffect, useRef } from 'react';

/**
 * DAVO's avatar — an abstract animated orb in the site palette, generated by
 * `scripts/generate-davo-avatar.mjs` (run it to regenerate both images).
 *
 * **Why a CSS sprite sheet and not a GIF.** Every avatar on the page has to show
 * the same frame at the same moment, and a GIF gives you no handle on playback
 * phase: an `<img>` added when an answer arrives starts its own timeline, so the
 * new orb drifts against the ones already on screen. Stepping a sprite sheet
 * with a CSS animation moves the whole thing onto the document timeline, where
 * `animation-delay` *is* a handle — see `LOOP_MS` below. It is also a third of
 * the bytes the GIF cost (106 KB vs 335 KB).
 *
 * **The green state is an overlay, not a `filter`.** It is absent from the DOM
 * when idle. The filter version left the header avatar stuck green on iOS Safari
 * after an answer finished: removing an infinite `filter` animation from a
 * composited element does not reliably repaint there. An element that is simply
 * unmounted cannot leave residue on any browser — and `mix-blend-mode: color`
 * takes hue from the overlay and luminosity from the orb, so it tints more
 * faithfully than the filter chain did (sky-300 lands on #6ae9bb, near
 * emerald-300, instead of going lime).
 *
 * **The component owns its own clip and glow** rather than being dropped into a
 * wrapper at each call site, because `thinking` has to change the glow and the
 * tint together — splitting that across three call sites is how they drift.
 */

/** Must match `davo-orb` in globals.css: FRAMES (32) * 60ms. */
const LOOP_MS = 1920;

/**
 * Seeks one orb so its loop is aligned to absolute document time.
 *
 * A CSS animation's clock starts when its element gets it, so an avatar created
 * three answers later begins at frame 0 while the others are mid-loop. Giving
 * each one `animation-delay: -(startTime % LOOP_MS)` makes its phase depend only
 * on the document timeline and not on when it mounted: at timeline position T
 * every orb sits at T % LOOP_MS, so they show the same frame without needing to
 * know about each other.
 */
function syncToDocumentTimeline(orb: HTMLElement): void {
  const [animation] = orb.getAnimations?.() ?? [];
  // `startTime` is the animation's true origin; `performance.now()` is a
  // fallback for browsers without getAnimations, off by the few ms between the
  // element being painted and this running — a fraction of one 60ms frame.
  const start = animation?.startTime;
  const t = typeof start === 'number' ? start : performance.now();
  orb.style.animationDelay = `${-(t % LOOP_MS)}ms`;
}

type DavoAvatarProps = {
  /**
   * Applied to the wrapper. Size and shape the avatar here (e.g.
   * `h-8 w-8 rounded-full`); the orb fills it and is clipped to it.
   */
  className?: string;
  /**
   * Empty where adjacent text already names DAVO, so a screen reader does not
   * hear the name twice.
   */
  alt?: string;
  /**
   * True while a request is in flight. Every avatar on the page shares one
   * value, so they pulse together rather than only the answer being written.
   *
   * Purely reinforcement: `WaitingIndicator` states the same thing in text
   * inside an `aria-live` region, so nothing is conveyed by colour alone.
   */
  thinking?: boolean;
};

export default function DavoAvatar({
  className = '',
  alt = 'DAVO',
  thinking = false,
}: DavoAvatarProps) {
  const orbRef = useRef<HTMLSpanElement>(null);

  // Done after mount rather than as an inline style: the value is clock-derived,
  // so rendering it on the server would fail hydration.
  useEffect(() => {
    const orb = orbRef.current;
    if (orb) syncToDocumentTimeline(orb);
  }, []);

  return (
    <span
      className={`relative isolate block overflow-hidden ${
        thinking ? 'davo-avatar--thinking' : 'shadow-[0_0_12px_rgba(167,139,250,0.35)]'
      } ${className}`}
    >
      <span
        ref={orbRef}
        className="davo-avatar__orb block h-full w-full"
        {...(alt ? { role: 'img', 'aria-label': alt } : { 'aria-hidden': true })}
      />
      {thinking && (
        <>
          {/* Hue from emerald-400, luminosity from the orb underneath. */}
          <span
            aria-hidden="true"
            className="pointer-events-none absolute inset-0 bg-emerald-400 mix-blend-color"
          />
          {/* The brightness half of the pulse; the glow and swell are on the wrapper. */}
          <span
            aria-hidden="true"
            className="davo-avatar__flare pointer-events-none absolute inset-0 mix-blend-screen"
          />
        </>
      )}
    </span>
  );
}
